package com.gqt.corejava.array_programming;
import java.util.Scanner;
/**
 * @author karthi v
 * @category Array
 * @description This is an example for Structured Array Program - Three Dimensional Array 
 */
class ArrayOperations2  {
	String arr[][][];
	Scanner sc = new Scanner(System.in);

	void createArray() {
		System.out.print("Enter the School count: ");
		int schl = sc.nextInt();
		System.out.print("Enter the Class count: ");
		int cls = sc.nextInt();
		System.out.print("Enter the Student count: ");
		int stu = sc.nextInt();
		
		//creating the 3D array
		arr = new String[schl][cls][stu];
		
		System.out.println("The array is created.");
		System.out.println("-------------------------------------");
	}

	void collectData() {
		for (int i = 0; i < arr.length; i++) {
			System.out.println("Inside the School no " + (i + 1));
			for (int j = 0; j < arr[i].length; j++) {
				System.out.println("Inside the Class no " + (j + 1));
				for(int k=0;k<arr[i][j].length;k++) {
					System.out.println("Enter the name of the Student no: " + (k + 1));
					arr[i][j][k]= sc.next();
				}
			}
		}
		System.out.println("Data is collected.");
		System.out.println("--------------------------------------");
	}

	void displayData() {
		for (int i = 0; i < arr.length; i++) {
			System.out.println("Inside the School no " + (i + 1));
			for (int j = 0; j < arr[i].length; j++) {
				System.out.println("Inside the Class no " + (j + 1));
				for(int k=0;k<arr[i][j].length;k++) {
					System.out.println("The name of the Student in school no: "+(i+1)+" is " + arr[i][j][k]);
				}
			}
		}
		System.out.println("---------------------------------");
	}

}

public class ArrayProgram3DStructured {

	/**
	 * @param args
	 * @description This contains source code for the Array Program
	 */
	public static void main(String[] args) {
		ArrayOperations2  ao = new ArrayOperations2 ();
		ao.createArray();
		ao.collectData();
		ao.displayData();
	}

}

//hemanth is th eowner is the production house named as eclipse production which is one of thee very renowned production house pan india.
//during the financial year 2024 to 2025 Hemanth had decided to produce 3 movies each under 3 categories in 3 languages each(kannada,hindi,Telegu),
//hementh had decided to invest a sum of 100 crores on this prticular films.
//at the end of the financial year hementh wanted to know revenue generated by each movie he halso wantede ro know profotable or not?.
//		additionaly he wanterd to know if he was made more profit than previous year which was 80 crores
//		depic the above scenario using revelent array concept.
